### ISSUE TITLE
Including substituents in composition images

### ISSUE THREAD

**Issue by kiyoko** [glycoinfo/GlycanBuilder2#14]
Display the substituents in composition images (from GlyGen)

**Comment by e15d5605** [comment]
529件の糖鎖構造のsvgを生成したが、データ量が多すぎるため検証方法を検討する。

**Comment by e15d5605** [comment]
以下の構造の可視化が困難だった

- G11148DZ
  - WURCS=2.0/4,4,3/[a2122h-1x_1-5_2\*NCC/3=O_6\*OSO/3=O/3=O][a1221m-1a_1-5][a2112h-1b_1-5][Aad21122h-2a_1-5\*N\*_2-6]/1-2-3-4/a3-b1_a4-c1_c3-d2
- G45987AL
  - WURCSを取得できない
- G30990DW
  - WURCS=2.0/4,4,3/[a1122h-1x_1-5][a2122h-1x_1-5_2\*NCC/3=O][a2112h-1x_1-5][a2122A-1x_1-5_3\*SO/2=O/2=O]/1-2-3-4/a?-b1_b?-c1_c?-d1 
- G53231FE
  - WURCS=2.0/4,4,3/[a2122h-1b_1-5_2\*NCC/3=O_6\*SO/2=O/2=O][a1221m-1a_1-5][a2112h-1b_1-5][Aad21122h-2a_2-6_5\*NCC/3=O]/1-2-3-4/a3-b1_a4-c1_c3-d2 
- G22929NZ
  - WURCS=2.0/3,3,2/[a2122h-1x_1-5_2\*NCC/3=O][a2112h-1x_1-5][a2122A-1x_1-5_3\*SO/2=O/2=O]/1-2-3/a?-b1_b?-c1
- G09409BX
  - WURCS=2.0/2,2,1/[a2122h-1x_1-5_2\*NCC/3=O][a2112h-1x_1-5_2\*NCC/3=O_4\*SO/2=O/2=O]/1-2/a?-b1
- G51907PX
  - WURCS=2.0/3,3,2/[a2122h-1b_1-5_2\*NCC/3=O][a1221m-1a_1-5][a2112h-1b_1-5_3\*SO/2=O/2=O]/1-2-3/a3-b1_a4-c1
- G74519IE
  - WURCS=2.0/3,3,2/[a2122h-1x_1-5_2\*NCC/3=O_6\*SO/2=O/2=O][a2112h-1x_1-5][Aad21122h-2x_2-6_5\*NCC/3=O]/1-2-3/a?-b1_b?-c2 
- G31301MT
  - WURCS=2.0/2,2,1/[a2122h-1x_1-5_2\*NCC/3=O][a2112h-1b_1-5_2\*NCC/3=O_4\*SO/2=O/2=O]/1-2/a4-b1 
- G06378CG
  - WURCS=2.0/4,4,3/[a2122h-1b_1-5_2\*NCC/3=O][a1221m-1a_1-5][a2112h-1b_1-5_6\*SO/2=O/2=O][Aad21122h-2a_2-6_5\*NCC/3=O]/1-2-3-4/a3-b1_a4-c1_c3-d2 
- G44854SQ
  - WURCS=2.0/3,3,2/[a2112h-1b_1-5][a2112h-1a_1-5][a2112h-1b_1-5_2\*NCC/3=O_3\*SO/2=O/2=O]/1-2-3/a4-b1_b3-c1 
- G83836YX
  - WURCS=2.0/4,4,3/[a2122h-1x_1-5_2\*NCC/3=O_6\*SO/2=O/2=O][a2112h-1x_1-5_6\*SO/2=O/2=O][Aad21122h-2x_2-6_5\*NCC/3=O][a1221m-1x_1-5]/1-2-3-4/a?-b1_a?-d1_b?-c2 
- G73699UT
  - WURCS=2.0/3,3,2/[a2122h-1b_1-5_2\*NCC/3=O_6\*SO/2=O/2=O][a2112h-1b_1-5][Aad21122h-2a_2-6_5\*NCC/3=O]/1-2-3/a4-b1_b3-c2 
- G95090DW
  - WURCS=2.0/1,1,0/[a2112h-1b_1-5_3\*SO/2=O/2=O]/1/ 
- G92341SR
  - WURCS=2.0/3,3,2/[a2122h-1b_1-5_2\*NCC/3=O_6\*SO/2=O/2=O][a2112h-1b_1-5][Aad21122h-2a_2-6_5\*NCC/3=O]/1-2-3/a4-b1_b6-c2 
- G99686YY
  - WURCS=2.0/4,4,3/[a2122h-1x_1-5][a2112h-1x_1-5][a2112h-1x_1-5_2\*NCC/3=O][a2112h-1x_1-5_3\*SO/2=O/2=O]/1-2-3-4/a?-b1_b?-c1_c?-d1 
- G99851EW
  - WURCS=2.0/4,4,3/[a2122h-1x_1-5_2\*NCC/3=O][a2112h-1x_1-5_6\*SO/2=O/2=O][Aad21122h-2x_2-6_5\*NCC/3=O][a1221m-1x_1-5]/1-2-3-4/a?-b1_a?-d1_b?-c2 
- G57036MA
  - WURCS=2.0/3,3,2/[a2112h-1b_1-5][a2112h-1a_1-5][a2112h-1b_1-5_2\*NCC/3=O_3\*SO/2=O/2=O]/1-2-3/a3-b1_b3-c1 
- G23094GH
  - WURCS=2.0/4,4,3/[a2122h-1b_1-5_2\*NCC/3=O_6\*SO/2=O/2=O][a1221m-1a_1-5][a2112h-1b_1-5_6\*SO/2=O/2=O][Aad21122h-2a_2-6_5\*NCC/3=O]/1-2-3-4/a3-b1_a4-c1_c3-d2 
- G82061CN
  - WURCS=2.0/4,4,3/[a1122h-1a_1-5][a2122h-1b_1-5_2\*NCC/3=O][a2112h-1b_1-5][a2122A-1b_1-5_3\*SO/2=O/2=O]/1-2-3-4/a2-b1_b4-c1_c3-d1 
- G14395NH
  - WURCS=2.0/3,3,2/[a2122h-1b_1-5_2\*NCC/3=O][a2112h-1b_1-5_3\*SO/2=O/2=O][a1221m-1a_1-5]/1-2-3/a3-b1_a4-c1 
- G89591DK
  - WURCS=2.0/3,3,2/[a2122h-1b_1-5_2\*NCC/3=O][a2112h-1b_1-5][a2122A-1b_1-5_3\*SO/2=O/2=O]/1-2-3/a4-b1_b3-c1 
- G29331WV
  - WURCS=2.0/3,3,2/[a2122h-1x_1-5_2\*NCC/3=O][a1221m-1x_1-5][a2112h-1x_1-5_3\*SO/2=O/2=O]/1-2-3/a?-b1_a?-c1 
- G37387PV
  - WURCS=2.0/2,3,2/[a2112h-1x_1-5][a2112h-1x_1-5_2\*NCC/3=O_3\*SO/2=O/2=O]/1-1-2/a?-b1_b?-c1 
- G97669BD
  - WURCS=2.0/2,2,1/[a2112h-1x_1-5][a2112h-1x_1-5_3\*SO/2=O/2=O]/1-2/a?-b1 
- G57796RK
  - WURCS=2.0/4,4,3/[a2122h-1b_1-5][a2112h-1b_1-5][a2112h-1b_1-5_2\*NCC/3=O][a2112h-1b_1-5_3\*SO/2=O/2=O]/1-2-3-4/a4-b1_b4-c1_c3-d1 
- G98482BC
  - WURCS=2.0/2,2,1/[a2112h-1b_1-5][a2112h-1b_1-5_3\*SO/2=O/2=O]/1-2/a4-b1 

単糖に結合した`*SO/2=O/2=O`は結合時に酸素を失っており, 慣用名を定義する際の機構が置換基の多様性に対応できていない.\
慣用名の定義はGlycanFormatConverterを利用しているが, GlycsanBuilderが利用しているのは古い処理である.\
また, 現状のGlycanBuilderではWURCSSequence2-Glycanへ直接変換を行なっており, 構造情報などの精査を行なっていない.\
最新のGlycanFormatConverterの処理に置き換えることで対応が可能と思われるが, 入力時にGlyContainerに変換されるためGlyContainer-Glycanオブジェクトの変換・解析処理を伴うこととなる.\

**Comment by MasaakiMatsubara** [comment]
@e15d5605 
上記コメントで議論している内容とは少しずれるかもしれませんが、`*SO/2=O/2=O`については、コンポジションの置換基の1つとして表示すべきかどうかについて議論の余地があると思います。
この置換基は、本来は`*OSO/2=O/2=O`となるところが、元々のGlycoCTの結合情報に誤りが含まれていたせいで、GlycoCTToWURCSによってこのような文字列に変換されたと考えられます。
そのため、置換基としての表現方法として、通常の硫酸基との区別が必要であると同時に、このような登録者の意図とは異なる誤った構造情報を他の通常の置換基と同列に扱うべきかどうかについても議論されるべきではないでしょうか。

@kiyoko @yamadaissaku 
硫酸基の誤った表現である`*SO/2=O/2=O`を置換基として表示可能にするかどうかについて、ご意見を伺いたいです。

**Comment by yamadaissaku** [comment]
* 「硫酸基の誤った表現である*SO/2=O/2=Oを置換基として表示可能にするかどうか」については、表示させる必要はないと思います。また、同様に間違った表現となっている置換基(MAP)も表示する必要はないと思います。これには硫酸基の他にリン酸基などが含まれる可能性があると思います。

* GlycanBuilder2としては、確認アラートを表示させるなどの対応をするのはどうでしょうか？

* 置換基として間違っていると考えられる糖鎖構造をGlyTouCanとしてどう対応するかについての課題を別課題としました。
  * https://gitlab.com/glycosmos/glycosmos-portal/-/issues/275

@kiyoko @e15d5605 @MasaakiMatsubara

**Comment by e15d5605** [comment]
_以下の変更点は検討が必要と思われるため, 現在はブランチで管理する._

> GlycanBuilder2としては、確認アラートを表示させるなどの対応をするのはどうでしょうか？

不適切な情報なので現状ではMAPの解析時に例外として以下のメッセージを返すようにした.\
このような例はリン酸基なども該当する.

> *SO/2=O/2=O is wrong MAP.

**Comment by MasaakiMatsubara** [comment]
@e15d5605 
> *SO/2=O/2=O is wrong MAP.

MAP文字列自体に間違いがある訳ではないので、このメッセージは正確ではないように思います。
単純に「このMAPはこのシステムでサポートされていない」ことを伝えれば良いと思います。

**Comment by e15d5605** [comment]
[Uploading glycans_without_images_wurcs.txt…]()

**Comment by yamadaissaku** [comment]
> _以下の変更点は検討が必要と思われるため, 現在はブランチで管理する._
> _masterにマージしてGlyGenに連絡する（20210330）_
> 
> > GlycanBuilder2としては、確認アラートを表示させるなどの対応をするのはどうでしょうか？
> 
> 不適切な情報なので現状ではMAPの解析時に例外として以下のメッセージを返すようにした.
> このような例はリン酸基なども該当する.
> 
> > *SO/2=O/2=O is wrong MAP.
> 
> 3月29日修正
> 
> > This MAP is not support in the GlycanBuilder2:*SO/2=O/2=O
> 
> ### MAP解析処理の仕組み
> GlycanFormatConverterのMAPAnalyzerというクラスを利用する.
> MAPAnalyzerに硫酸基（*OSO/3=O/3=O）を入力するとheadに酸素を持つという解析結果が返される.
> GlycanBuilderではMAP解析後のMAPAnalyzerのheadがnullの場合は対応困難な置換基として例外処理を行う.
> NやN-acetylなどのMAPの先頭に酸素が表記されていない置換基は該当しない.
> 
> （20210409追加）
> F, Cl, Br, I, Sなどの酸素を持たないMAPが該当してしまっていたため条件の修正を検討.
> 
> ### 単糖の読み込み処理変更に伴う仕様変更
> また, 単糖の読み込み処理を最新のものに変更したことで以下の単糖は例外となる. 
> （xまたはXとそれ以外のCarbonDescriptorが混在するSkeletonCodeから正確な単糖名を定義することは困難なため）
> 
> > AUdxxxxxh_5*NCC/3=O
> > uxxFFA

**Comment by kiyoko** [comment]
https://gitlab.com/glycosmos/gfc/-/issues/22 が完了次第？
