### ISSUE TITLE
Image generation for glycan G29731EF by WURCS

### ISSUE THREAD

**Issue by Hendricks27** [glycoinfo/GlycanBuilder2#15]
I am able to generate the image by GlycoCT, but not by WURCS. 
Here are the error messages.

![image](https://user-images.githubusercontent.com/33260365/115497375-8863a780-a239-11eb-90c0-bfa2037df4e1.png)

**Comment by e15d5605** [comment]
This problem occurred by old version of GlycanFormatConverter (2.5.2).
GlycanFormatConverter is a dependency of GlycanBuilder2.
We fixed this problem and released a dependency of latest version of GlycanBuilder2.
Please you run `git pull` in the directory of GlycanBuilder2.
