### ISSUE TITLE
Modification of glycan structure template

### ISSUE THREAD

**Issue by yamadaissaku** [glycoinfo/GlycanBuilder2#25]
https://www.ncbi.nlm.nih.gov/books/NBK453020/figure/ch9.f1/?report=objectonly

Update of Oligomannose and Complex Glycan structure and addition of Hybrid N-glycan

source: https://github.com/glycoinfo/GlycanBuilder2/blob/master/src/main/resources/conf/core_types

**Comment by e15d5605** [comment]
N-結合型糖鎖のHybridとComplexに対応をしたいのだが、末端に`Sia`を持つため現状では対応が難しい

**Comment by yamadaissaku** [comment]
@e15d5605 Siaではなく、Nue5Ac でいいのでは？ 構造は　https://www.ncbi.nlm.nih.gov/books/NBK453020/　ここで確認しましょう。上記に加えて、Glc3Man9GlcNAc2　があると便利と思いました。

**Comment by e15d5605** [comment]
@yamadaissaku 山田さんのおっしゃるようにNeu5Acでも良いのかとは思ったのですが、画像を見ると赤菱形シンボルなので、そちらに準拠する必要があるのかと考えておりました。チャプター9にもN結合型糖鎖の末端の赤菱形シンボルに関して言及されていなかったので、Siaに関して解説しているチャプター15を読んでみました。そこで、ヒトの最も一般的なSiaはNeu5Acと記載されていたのは確認しました。
また、Glc3Man9GlcNAc2は以下の構造で正しいでしょうか？
![image](https://user-images.githubusercontent.com/15099705/146297018-dbb4efb0-0349-4edf-95bc-85ae0c69cc60.png)

**Comment by e15d5605** [comment]
GlycanBuilderのテンプレートファイルを更新してN-Glycanに以下の項目を追加した
![image](https://user-images.githubusercontent.com/15099705/146323832-97bce8b8-5765-45ed-b5ba-c302cdc2c798.png)

* N-glycan complex
```
ncorecomplex	N-glycans		freeEnd--?b1D-GlcNAc,p(--4b1D-GlcNAc,p--4b1D-Man,p(--3a1D-Man,p--2b1D-GlcNAc,p--4b1D-Gal,p--6a2D-NeuAc,p)--6a1D-Man,p--2b1D-GlcNAc,p--4b1D-Gal,p--6a2D-NeuAc,p)--6a1L-Fuc,p	 N-glycan complex 
```
![image](https://user-images.githubusercontent.com/15099705/146324210-c8f60a95-a8b8-43d9-ae03-1ae9a67e75a4.png)


* N-glycan hybrid
```
ncorehybrid	N-glycans		freeEnd--?b1D-GlcNAc,p--4b1D-GlcNAc,p--4b1D-Man,p(--3a1D-Man,p--2b1D-GlcNAc,p--4b1D-Gal,p--6a2D-NeuAc,p)--6a1D-Man,p(--3a1D-Man,p)--6a1D-Man,p	 N-glycan hybrid
```
![image](https://user-images.githubusercontent.com/15099705/146324249-3091ba5d-08ea-4168-8d07-bbe8248d0fa1.png)

* N-glycan oligosaccharide
```
ncoreoligosaccharide	N-glycans		freeEnd--?a1D-GlcNAc,p--4b1D-GlcNAc,p--4b1D-Man,p(--3a1D-Man,p--2a1D-Man,p--2a1D-Man,p--3a1D-Glc,p--3a1D-Glc,p--2a1D-Glc,p)--6a1D-Man,p(--3a1D-Man,p--2a1D-Man,p)--6a1D-Man,p--2a1D-Man,p	 N-glycan oligosaccharide
```
![image](https://user-images.githubusercontent.com/15099705/146324273-95f453de-2d16-4f41-85cc-088f5c78c218.png)

N-Glycanの更新に合わせてreducing endに`Asn`を追加した方がいいかもしれない

**Comment by e15d5605** [comment]
v1.16.0としてリリースしたためClose

還元末端に関しては別に課題を立てているためそちらで議論する
