### ISSUE TITLE
Exception when trying to start GlyanBuilder2 

### ISSUE THREAD

**Issue by juliastic** [glycoinfo/GlycanBuilder2#63]
Hello!

When trying to start the application with `java -XstartOnFirstThread -jar ./target/glycanbuilder2-jar-with-dependencies.jar`, I get the following error in the terminal: 
`Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/swt/SWT
at chrriis.dj.nativeswing.swtimpl.NativeInterface.initialize(NativeInterface.java:183)`

I'm using a M1 MBP running macOS Ventura 13.4.1. I've tried to manually add both the DJNativeSwing-SWT and DJNativeSwing jars to project's class path but to no avail:
`java -cp DJNativeSwing-SWT.jar:DJNativeSwing.jar  -XstartOnFirstThread -jar ./target/glycanbuilder2-jar-with-dependencies.jar`

My guess is that there is an issue with the class path in the project's DJNativeSwing and DJNativeSwing-SWT entries.

Any input is appreciated! Thank you!

**Comment by yamadaissaku** [comment]
Hi Julia,

If you are using macOS with M1 architecture, you can use GlycanBuilder2.app from the following website.

[https://gitlab.com/GlycoTool/dev-version/-/tree/master/GlycanBuilder/mac?ref_type=heads](https://gitlab.com/GlycoTool/dev-version/-/tree/master/GlycanBuilder/mac?ref_type=heads)

Also, the library dependency problem is under consideration for a solution, and it will take some time.

**Comment by juliastic** [comment]
Thanks for your quick response! I'll go ahead and close this ticket as a workaround has been provided.
