### ISSUE TITLE
描画エラーへの対応

### ISSUE THREAD

**Issue by e15d5605** [glycoinfo/GlycanBuilder2#8]
## Overview

ユーザーからの報告やGlyCosmosプロジェクトで上がっているものを列挙
本格的に取り掛かる場合に個別のトピックを作成、または既存のトピックへ追加

- https://gitlab.com/glycosmos/support/-/issues/4
- https://gitlab.com/glycosmos/support/-/issues/7
- https://gitlab.com/glycosmos/glytoucan/gtc-glycanbuilder/-/issues/1
- https://gitlab.com/glycosmos/glycosmos-portal/-/issues/56
- https://gitlab.com/glycosmos/glycosmos-portal/-/issues/85

**Comment by kiyoko** [comment]
@e15d5605 
このissueは開く必要ありますか？

**Comment by e15d5605** [comment]
@kiyoko 
GlycanBuilder2を使用した際に問題が発生したら、このissueに追記するという運用方法を想定していました\
現在はGlycanBuilder2に問題が発生した場合は、その都度issueを作成しているので不要です\
Closeいたします
